Metrics/MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "**/*_controller.rb*"
Style/FileName:
  Exclude:
    - "Gemfile"
Style/BlockDelimiters:
  Exclude:
    - "spec/**/*.rb"
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
Documentation:
  Enabled: false

Metrics/LineLength:
 Exclude:
   - "spec/**/*.rb"
Metrics/ModuleLength:
 Exclude:
   - "**/*.rb"
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
 Exclude:
   - "**/*.rb"

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7
